### ISSUE TITLE
File is not created using --outputFile

### ISSUE THREAD

**Issue by denuxs** [RESOStandards/web-api-commander#131]
Hi, team

I am trying to download data to json but the file is not created

`docker run -it web-api-commander --saveGetRequest --uri='https://api.mls.com/api/v2/OData/imls/Property?$top=10' --bearerToken xxx --outputFile /home/response.json`

openjdk 11.0.16 2022-07-19
OpenJDK Runtime Environment (build 11.0.16+8-post-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)

**Comment by darnjo** [comment]
Thanks for opening this ticket. 

When using this command with Docker, the `outputFile` will actually be in the container's filesystem and not local. 

In order to make the output local, you'll need to mount a local volume to the Docker container, and then use that path as the output path. There is some information here: https://commander.reso.org/doc/Docker.html#commander-utilities

For example: `docker run -it -v $PWD:/app web-api-commander --validateMetadata --inputFile <pathInContainer> --outputFile /app/response.json`

This should mount your current directory into a folder called `/app` in the container, and when the file is written, you should see the output in your current directory. 

Let me know if you have any further issues or questions.

**Comment by darnjo** [comment]
@denuxs - did you have any more questions on this one? Did the previous reply resolve your question?
