### ISSUE TITLE
Missing files?

### ISSUE THREAD

**Issue by janwelten** [RESOStandards/web-api-commander#132]
Doc for command line commander says; 
"Once the Java SE Runtime is installed, you may download the Commander JAR file"

Clicking the link gives me a file-not found error;
"The 'RESOStandards/web-api-commander' repository doesn't contain the 'doc/build/libs/web-api-commander.jar' path in 'main'."

I can't find that file anywhere in the file structure.. anyone?

Thank you! :)

**Comment by cobogeri** [comment]
I found it at:
https://github.com/RESOStandards/web-api-commander/releases

**Comment by darnjo** [comment]
Hi. Thanks for the follow up. 

As you noticed, we stopped publishing the JAR file in the GitHub source code since we wanted to try to make things a bit smaller, and moved it to the release artifacts. 

We will update the documentation, and then close this issue. 

There are two additional ways you can work with the JAR as well: 
* By building a Docker Container, as outlined here: https://commander.reso.org/doc/Docker.html#commander-utilities
* By using "gradlew" after you check out the repository, assuming you have Java JDK (version 8 or above) installed, by using the command `./gradlew build`. 

Out of curiosity, are you using this for RESO Certification, or as an OData client?
