### ISSUE TITLE
Validate metadata separately from web API cert tests

### ISSUE THREAD

**Issue by dgmyrek** [RESOStandards/web-api-commander#19]
@darnjo, opened this one up per our email discussion. 

When server metadata doesn't 100% pass validation a number of totally unrelated web API cert tests fail. Here's one example:

And resource metadata for "Parameter_EndpointResource" contains the fields in the given select list
     java.lang.AssertionError: ERROR: Field name 'ListingKey' is not present in server metadata!

I can verify with 100% certainty that the ListingKey and BedsTotal fields are both in the metadata (although for the purpose of this test should that even matter?), so I'm wondering if it's choking on another aspect of the validation and throwing a false negative. 

@REQ-WA103-QO4 @core @2.4.4 @filterability-endorsement
Scenario: REQ-WA103-QO4 - Query Support: $filter - Integer Comparison: gt                             # src/main/java/org/reso/certification/features/web-api/web-api-server-1.0.2.feature:141
Using RESOScript: generic.gold.resoscript
  Given a RESOScript file was provided                                                                # org.reso.certification.stepdefs.WebAPIServer_1_0_2.<init>(WebAPIServer_1_0_2.java:73)
RESOScript loaded successfully!
  And Client Settings and Parameters were read from the file                                          # org.reso.certification.stepdefs.WebAPIServer_1_0_2.<init>(WebAPIServer_1_0_2.java:80)
Service root is: https://api.flexmls.com/Reso/OData
  And a test container was successfully created from the given RESOScript                             # org.reso.certification.stepdefs.WebAPIServer_1_0_2.<init>(WebAPIServer_1_0_2.java:88)
Authentication Type: authorization_code
  And the test container uses an authorization_code or client_credentials for authentication          # org.reso.certification.stepdefs.WebAPIServer_1_0_2.<init>(WebAPIServer_1_0_2.java:95)
Request ID: REQ-WA103-QO4
Request URI: https://api.flexmls.com/Reso/OData/Property?$top=5&$select=ListingKey,BedroomsTotal&$filter=BedroomsTotal%20gt%209
Request succeeded...1018 bytes received.
  When a GET request is made to the resolved Url in "REQ-WA103-QO4"                                   # org.reso.certification.stepdefs.WebAPIServer_1_0_2.<init>(WebAPIServer_1_0_2.java:311)
Asserted Response Code: 200, Server Response Code: 200
  Then the server responds with a status code of 200                                                  # org.reso.certification.stepdefs.WebAPIServer_1_0_2.<init>(WebAPIServer_1_0_2.java:316)
Reported OData-Version header value: '4.0'
  And the server has an OData-Version header value of "4.0" or "4.01"                                 # org.reso.certification.stepdefs.WebAPIServer_1_0_2.<init>(WebAPIServer_1_0_2.java:1019)
Response is valid JSON!
Response: {
  "@odata.context" : "https://api.flexmls.com/Reso/OData/$metadata#Property",
  "@odata.nextLink" : "https://api.flexmls.com/Reso/OData/Property?%24filter=BedroomsTotal+gt+9&%24select=ListingKey%2CBedroomsTotal&%24skiptoken=20140916145247358266000000&%24top=5",
  "value" : [ {
    "ListingKey" : "20140916144954333968000000",
    "BedroomsTotal" : 12,
    "@odata.id" : "https://api.flexmls.com/Reso/OData/Property('20140916144954333968000000')"
  }, {
    "ListingKey" : "20140916145028952092000000",
    "BedroomsTotal" : 14,
    "@odata.id" : "https://api.flexmls.com/Reso/OData/Property('20140916145028952092000000')"
  }, {
    "ListingKey" : "20140916145039632072000000",
    "BedroomsTotal" : 10,
    "@odata.id" : "https://api.flexmls.com/Reso/OData/Property('20140916145039632072000000')"
  }, {
    "ListingKey" : "20140916145146671730000000",
    "BedroomsTotal" : 10,
    "@odata.id" : "https://api.flexmls.com/Reso/OData/Property('20140916145146671730000000')"
  }, {
    "ListingKey" : "20140916145247358266000000",
    "BedroomsTotal" : 11,
    "@odata.id" : "https://api.flexmls.com/Reso/OData/Property('20140916145247358266000000')"
  } ]
}
  And the response is valid JSON                                                                      # org.reso.certification.stepdefs.WebAPIServer_1_0_2.<init>(WebAPIServer_1_0_2.java:353)
Results count is: 3
  And the response has results                                                                        # org.reso.certification.stepdefs.WebAPIServer_1_0_2.<init>(WebAPIServer_1_0_2.java:421)
Searching metadata for fields in given select list: [ListingKey, BedroomsTotal]
  And resource metadata for "Parameter_EndpointResource" contains the fields in the given select list # org.reso.certification.stepdefs.WebAPIServer_1_0_2.<init>(WebAPIServer_1_0_2.java:771)
      java.lang.AssertionError: ERROR: Field name 'ListingKey' is not present in server metadata!
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.assertTrue(Assert.java:42)
        at org.junit.Assert.assertNotNull(Assert.java:713)
        at org.reso.certification.stepdefs.WebAPIServer_1_0_2.lambda$null$44(WebAPIServer_1_0_2.java:779)
        at ?.resource metadata for "Parameter_EndpointResource" contains the fields in the given select list(file:web-api-commander-master/src/main/java/org/reso/certification/features/web-api/web-api-server-1.0.2.feature:147)

If the metadata is the blocker on these tests it may even be better to outright refuse to fully execute the suite until a set of metadata tests pass, thus turning it into a two step process:

1. Run metadata tests and verify all is well
2. Run web API cert

That feels quite a bit more performant compared to looping through metadata tests as a part of each individually web API cert scenario and makes the suite more resilient overall - eg. you can be sure that a failure in a test is related to the actual functionality you're trying to test.

**Comment by darnjo** [comment]
The issue here is that we're now doing metadata-related checks on each of the subsequent tests to ensure that the fields used in the queries are in the metadata (have found cases where that's not true), as well as using it and intending on using the metadata checks for other things. 

However, if the following tests don't pass, those subsequent tests won't necessarily pass:
- [Validate metadata response XML](https://github.com/RESOStandards/web-api-commander/blob/master/src/main/java/org/reso/certification/features/web-api/web-api-server-1.0.2.feature#L22) to ensure it's valid and matches the XSDs published by OASIS. 
- [Validate XML Metadata object](https://github.com/RESOStandards/web-api-commander/blob/master/src/main/java/org/reso/certification/features/web-api/web-api-server-1.0.2.feature#L23) (in Olingo) and use metadata validator to ensure it matches expectations.
- [Validate Edm](https://github.com/RESOStandards/web-api-commander/blob/master/src/main/java/org/reso/certification/features/web-api/web-api-server-1.0.2.feature#L27) (entity data model) and make sure it has things like a service document and default container. 

Given these dependencies, it makes sense to add code to ensure that no test can run if it depends on metadata tests which possibly haven't passed. 

There are two ways we could accomplish this. One is to add an additional condition to each of those tests as a statement. Perhaps something like `Given all metadata checks were successful...`. Alternatively, we could put the metadata checks in the Background section of the Gherkin script and not repeat them if metadata are present and they've passed so that we don't slow down the tests.

It might be nice to have the metadata dependency specifically in the tests that use it because we have tests like the DataSystem or Response Code tests that don't actually depend on metadata and the Background would include those checks anyway? I suppose given what we've said above, maybe that's not necessary if nothing should proceed if the metadata checks fail? 

(cc: @EnFinlay curious to hear your thoughts on this too).

**Comment by darnjo** [comment]
It's worth noting that I've already added code to resolve the metadata dependencies in the case where one or more tests are run (such as by tag filtering) as opposed to all of the tests in order. This is also needed for interactive debugging in IntelliJ. Things may take slightly longer in this case as the metadata and Edm have to be fetched, but are then cached in memory after that as it's highly unlikely metadata would change during the course of a test run.

**Comment by darnjo** [comment]
Perhaps give it a try when you get a chance.

**Comment by EnFinlay** [comment]
Looks pretty good to me!

**Comment by darnjo** [comment]
@dgmyrek any thoughts? 
I'm going to tidy up a few things and then make a PR.

**Comment by darnjo** [comment]
@dgmyrek this should be ready to test/close out.
