### ISSUE TITLE
Incorrect behavior with case-sensitivity in some tests

### ISSUE THREAD

**Issue by jerretrobison** [RESOStandards/web-api-commander#24]
Consider making these tests case-insensitive:
REQ-WA103-QO13
REQ-WA103-QO14
REQ-WA103-QO15

These tests are likely noops in some databases:
REQ-WA103-QO16 (tolower)
REQ-WA103-QO17 (toupper)

Should these queries return the same count?
https://host/OData/DDv1.7/Property/$count?$filter=StreetName eq 'MAIN'
https://host/OData/DDv1.7/Property/$count?$filter=StreetName eq 'main'

Or these queries?
https://host/OData/DDv1.7/Property/$count?$filter=contains(StreetName, 'MAIN')
https://host/OData/DDv1.7/Property/$count?$filter=contains(StreetName, 'main')

The answer depends on the collation settings used by the underlying database. The OData and RESO specifications don't seem to offer an explicit opinion on the case-sensitivity of string values. The tests should be agnostic to casing to accommodate a given implementation's unspecified database collation settings.

**Comment by darnjo** [comment]
Hi Jerret. Thanks for reporting this. 

Some preliminary findings:

OData used to have [`edm:Collation`](https://www.odata.org/documentation/odata-version-3-0/common-schema-definition-language-csdl/) prior to version 4.x, but they have since removed this from the specification. 

The OData ABNF uses `primativeLiteral` for the RHS of these comparison operations, which is [described here](https://docs.oasis-open.org/odata/odata/v4.0/errata03/os/complete/abnf/odata-abnf-construction-rules.txt). In this case, the item of interest is `string`, which is defined as follows: `string= SQUOTE *( SQUOTE-in-string / pchar-no-SQUOTE ) SQUOTE`.

It's my understanding that OData String comparisons are case-sensitive, according to Unicode comparison rules. In order to ensure comparisons work as intended, `tolower` and `toupper` should be used. 

The OData 4.0 errata 03 specification says the following regarding these functions: 

> The tolower function returns the input parameter string value with all uppercase characters converted to lowercase according to Unicode rules. 

> The toupper function returns the input parameter string value with all lowercase characters converted to uppercase according to Unicode rules

Unfortunately, [OData 4.0 errata03](http://docs.oasis-open.org/odata/odata/v4.0/errata03/os/complete/part2-url-conventions/odata-v4.0-errata03-os-part2-url-conventions-complete.html#_Toc453752358) isn't as clear on String comparisons and equality as it could be, but note that this has been clarified in OData 4.01 in the section on [String and Collection functions](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#_Toc31360980).

From [this document](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#_Toc31361028), 

> 5.1.1.5.2 contains
> The contains function has two overloads, with the following signatures:
>
> Edm.Boolean contains(Edm.String,Edm.String)
> Edm.Boolean contains(OrderedCollection,OrderedCollection)
>
> The contains function with string parameter values returns true if the second string is a substring of the first string, otherwise it returns false. String comparison is **case-sensitive**, case-insensitive comparison can be achieved in combination with tolower or toupper.
>
> The contains function with ordered collection parameter values returns true if the first collection can be transformed into the second collection by removing zero or more items from the beginning or the end of the first collection.
>
> Example 70: all customers with a CompanyName that contains 'Alfreds'
> ```http://host/service/Customers?$filter=contains(CompanyName,'Alfreds')```

The remaining string comparison functions `startswith`, `endswith`, `indexof` are defined similarly. I do not believe these are requirements that were added in [4.01](http://docs.oasis-open.org/odata/odata/v4.01/cs01/abnf/odata-abnf-construction-rules.txt), as the ABNFs for `string` is the same in both versions. Rather, it was likely not clarified sufficiently in 4.0. 

As such, `Main` == `main` is expected to be `false`, but `toupper('Main')` == `toUpper('main')` is expected to be `true`.

This is probably a good item to bring up in the workgroups for further discussion and clarification.

**Comment by jerretrobison** [comment]
Thanks for doing that research. I'd also like to see this brought up in the workgroup. I agree with your reasoning, but it was quite a walk to reach the conclusion. If nothing else, the requirement should made clear in the specification.

**Comment by darnjo** [comment]
I've surfaced the issue issue and it should be discussed in the Transport meeting Monday, at 1pm PT. There's more info on the RESO calendar.

**Comment by sledwith** [comment]
Had a good discussion about this today during the Certification Subgroup meeting. More discussion to come, but we're leaning towards case insensitive query.

**Comment by darnjo** [comment]
I think it's a bit early to say still. The spec is clear that case-sensitivity is a requirement in 4.01 (linked above). I think we need to be cautious about deviating from a MUST requirement in out underlying transport, whether it makes sense in our case or not. That's kind of what it means to base our standard on an existing spec. We use it.

**Comment by darnjo** [comment]
This issue was discussed in the Certification Subgroup and since it's not currently part of Web API Core, the item is on hold until string tests are implemented.

To restate, the OData specification requires case-sensitivity in queries. I'm not sure there's a way around that since it's explicitly mentioned in the OData specification, whether it makes sense or not.

**Comment by darnjo** [comment]
The case-sensitive behavior is as expected by the OData spec. However, we will not test this functionality at this time.
