### ISSUE TITLE
XSLT possibly non-functional

### ISSUE THREAD

**Issue by fbstim** [RESOStandards/web-api-commander#29]
Generating OAS doc using current build fails to create valid JSON doc, possibly due to https://github.com/oasis-tcs/odata-openapi/blob/master/tools/V4-CSDL-to-OpenAPI.xsl

**Comment by darnjo** [comment]
Perhaps you can provide some more details? Kind of hard to troubleshoot from this report.

**Comment by darnjo** [comment]
Thanks for reporting this. Would it be possible to get some more information here so we can debug this? 

Since the [XSLT we use to translate the schema to Open API is something that is produced by OASIS](https://github.com/oasis-tcs/odata-openapi/blob/master/tools/V4-CSDL-to-OpenAPI.xsl), you'll likely want to open a ticket there.

**Comment by darnjo** [comment]
Note that this functionality has been deprecated in favor of the NodeJS version. See the odata-openapi folder under the main project (currently only in the dd-test-generator branch, but will be merged once it's PR'd).
